<a href="https://colab.research.google.com/github/nadjakencana/2025_Kecerdasan_Buatan_TI1b/blob/main/JobSheet_4_Kecerdasan_Buatan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Latihan 1 Jobsheet 4 Kecerdasan Buatan

In [ ]:
import pandas as pd

df = pd.read_csv('./data.csv')
print(df.to_string())
df
pd.options.display.max_rows
pd.options.display.max_rows = 9999

df = pd.read_csv('./data.csv')
df

In [ ]:
import pandas as pd

df = pd.read_json('./data.json')
print(df.to_string())

In [ ]:
df = pd.read_csv('./data.csv', sep=',', header=0)
df

In [7]:
data = {
  "Duration": { "0":60, "1":60, "2":60, "3":45 },
  "Pulse": { "0":110, "1":117, "2":103, "3":109 },
  "Maxpulse": { "0":130, "1":145, "2":135, "3":175 },
  "Calories": { "0":409, "1":479, "2":340, "3":282 }
}

df = pd.DataFrame(data)
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282

# Latihan 2 Jobsheet 4 Kecerdasan Buatan

In [ ]:
import pandas as pd

li = [1, 7, 2]
se = pd.Series(li)
print(se)

In [ ]:
li = [1, 7, 2]
se = pd.Series(li)
print(se[0])

In [ ]:
li = [1, 7, 2]
se = pd.Series(li, index = ['x', 'y', 'z'])
print(se['x'])

In [ ]:
calories = {"day1": 420, "day2": 380, "day3": 390}
se = pd.Series(calories)
print(se)

# Latihan 3 JobSheet 4 Kecerdasan Buatan

In [9]:
import pandas as pd

df = pd.DataFrame(data={"Nama": ["Budi", "Joko", "Adi"], "Umur": [12, 13, 15], "Kelas": [6, 7, 8]})
df
df.columns
df.columns.values[0] = "Nama Singkat"
df
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [10]:
df.iloc[0:2, 0:1]
df.iloc[0:2, 0:2]
df.iloc[:, 0:2]
df.loc[0:2, ['calories']]
df.loc[0:2, ['calories', 'duration']]
df['calories']
df['calories'][0]
df[['calories']]
df[['calories']].loc[[0, 1]]

   calories
0       420
1       380

In [11]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [ ]:
df = pd.read_csv('./data.csv')
print(df)
df
df.head()
df.tail()
df.head(10)
df.shape
df.dtypes

In [13]:
df.info()
df.describe()
print(df['Calories'].mean(), df['Calories'].median(), df['Calories'].mode()[0])
df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
375.79024390243904 318.6 300.0

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

# Praktikum JobSheet 4 Kecerdasan Buatan

In [ ]:
import pandas as pd

#Mengubah DataSet menjadi Data Frame
df = pd.read_csv('./epl-goalScorer(20-21).csv')

In [ ]:
# Ambil 5 data pertama
print(df.head())

In [ ]:
# Tampilkan Jumlah Barsi dan Kolom
print(df.shape)

In [ ]:
# Tampilkan tipe data dari tiap kolom
print(df.dtypes)

In [ ]:
# Jumlah Goal tiap Pemain
print(df[['Player', 'Goals']])

In [ ]:
# DAtaframe berisi kolom tertentu
print(df[['Player', 'Goals', 'Position', 'Club', 'Yellow_Cards']])

In [ ]:
# Pemain Liverpool
print(df[df['Club'] == 'Liverpool'])

In [ ]:
# Pemain arsenal
print(df[df['Club'] == 'Arsenal'])

In [ ]:
# Top 10 kartu kuning
top_yellow = df.sort_values(by='Yellow_Cards', ascending=False)
print(top_yellow.head(10))

In [ ]:
# Top 10 Kartu merah
top_red = df.sort_values(by='Red_Cards', ascending=False)
print(top_red.head(10))